### ISSUE TITLE
FR: Support roles plugin

### ISSUE THREAD

**Issue by dploeger** [ColdTrick/profile_manager#109]
It would be great, if you could choose, which roles from the [roles plugin](https://elgg.org/plugins/847275) can edit or view a field.

**Comment by jdalsem** [comment]
i understand your wish, but i do not see it happen anytime soon that this is going to be part of the profile_manager plugin. 

I think it would make more sense if this feature is added via the roles plugin, rather than via profile_manager, as profile fields also exist without the profile_manager plugin. 

You could also create a separate plugin that does the integration.
