### ISSUE TITLE
validation for the website(url) profile field

### ISSUE THREAD

**Issue by YanweiJiang** [ColdTrick/profile_manager#97]
I am using the profile manager and imported the default profile fields, but the website field's validation is not perfect. You have to enter http protocol to pass the validation. mysite.com and www.mysite.com won't pass the validation. Funny thing is if you enter http:www.mysite.com, the validation passes and insert a http protocol before it like http://http:www.mysite.com, which is totally wrong. I tried to look into those files but could not find where I can add some custom validation, can you give me a hint please? Thanks

**Comment by jdalsem** [comment]
This is caused by the fact that url validation is divided between html URL validation during input where `www.mysite.com` is not a valid URL and something with a (or any) protocol is.

Currently serverside the profile field is validated for having a http:// or https:// start and updated if it is missing, causing your issue. This is however not part of the profile_manager plugin, but from Elgg core.

There is already a issue related to this problem https://github.com/Elgg/Elgg/issues/6569
